services:
  react-app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${FRONTEND_PORT}:5173"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - APP_NAME=${APP_NAME:-React App}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - API_URL=${API_URL:-http://localhost:8000}
      - DEBUG=${DEBUG:-true}
    volumes:
      - ../app:/app
      - /app/node_modules
    networks:
      - frontend-network
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "/app/docker/scripts/health_check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3

networks:
  frontend-network:
    driver: bridge
